apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1-deployment
  namespace: app1-namespace
  labels:
    app: app1
spec:
  replicas: 3 
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
        - name: app1-container
          image: busybox
          command: ["/bin/sh", "-c", "sleep 4800"]
